services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "9081:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../OrderTrackingSystem:/var/www/laravel
    depends_on:
      - pgsql
      - php

  php:
    build:
      context: ./docker/dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ../OrderTrackingSystem:/var/www/laravel
    environment:
      - DB_HOST=pgsql
      - REDIS_HOST=redis
    depends_on:
      - pgsql
      - redis

  pgsql:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - docker/env/pgsql.env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  composer:
    build:
      context: ./docker/dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ../OrderTrackingSystem:/var/www/laravel

  artisan:
    build:
      context: ./docker/dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ../OrderTrackingSystem:/var/www/laravel
    entrypoint: [ "php", "/var/www/laravel/artisan" ]
    depends_on:
      pgsql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DB_HOST=pgsql
      - REDIS_HOST=redis
    command: [ "migrate" ]
  horizon:
      build:
        context: ./docker/dockerfiles
        dockerfile: php.Dockerfile
      volumes:
        - ../OrderTrackingSystem:/var/www/laravel
      depends_on:
        - redis
        - pgsql
      environment:
        - DB_HOST=pgsql
        - REDIS_HOST=redis
      command: php artisan horizon

volumes:
  db_data:
  redis_data:
